SM=35
ARCH = -arch sm_$(SM)

# Build Data
BUILD_SYSTEM=$(OS)

BUILD_DATA = -DBUILD_SYSTEM=\"$(BUILD_SYSTEM)\" -DBUILD_SM=\"$(SM)\"

source = genga.cu Host2.cu Orbit2.cu Energy.cu output.cu integrator.cu gas.cu 
headers = define.h Host2.h Orbit2.h FG2.h BSSingle.h Encounter3.h Kick3.h Kick4.h HC.h BSB.h BSBM.h BSB64M.h BSA.h ComEnergy.h directAcc.h force.h forceYarkovskyOld.h TTVStep2.h BSTTV.h  BSRV.h Scan.h Rcrit.h convert.h createparticles.h
genga: $(source) $(headers)
	nvcc $(ARCH) -o genga $(source) $(BUILD_DATA)
